version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: calculator
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    networks:
      - app-network

  frontend:
    build: ../frontend
    ports:
      - "5173:80"   # host:container
    networks:
      - app-network
    depends_on:
      - api-gateway

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    env_file:
      - ./api-gateway/.env.docker  
    networks:
      - app-network
    depends_on:
      - auth-service
      - balance-service
      - operation-service
      - record-service

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "4000:4000"
    env_file:
      - ./auth-service/.env.docker  
    networks:
      - app-network
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/calculator
    depends_on:
      - postgres
      - minio

  balance-service:
    build: ./balance-service
    container_name: balance-service
    ports:
      - "4003:4003"
    env_file:
      - ./balance-service/.env.docker  
    networks:
      - app-network
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/calculator
    depends_on:
      - postgres

  operation-service:
    build: ./operation-service
    container_name: operation-service
    ports:
      - "4001:4001"
    env_file:
      - ./operation-service/.env.docker  
    networks:
      - app-network
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/calculator
    depends_on:
      - postgres
      - balance-service
      - record-service

  record-service:
    build: ./record-service
    container_name: record-service
    ports:
      - "4002:4002"
    env_file:
      - ./record-service/.env.docker  
    networks:
      - app-network
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/calculator
    depends_on:
      - postgres

networks:
  app-network:
    driver: bridge      

volumes:
  postgres-data:
  minio-data:
