name: Backend CI (api-gateway only)

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

concurrency:
  group: backend-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  api-gateway-ci:
    name: api-gateway - Install → Lint → Test → Build
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./api-gateway

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: ./api-gateway/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Lint (if script exists)
        run: |
          if npm run | grep -q "lint"; then
            npm run lint
          else
            echo "No lint script found in api-gateway, skipping."
          fi

      - name: Run tests with coverage
        run: |
          if npm run | grep -q "test:ci"; then
            npm run test:ci
          else
            npx jest --coverage --runInBand
          fi
        env:
          NODE_ENV: test

      - name: Upload coverage artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-api-gateway
          path: ./api-gateway/coverage

      - name: Build (if script exists)
        run: |
          if npm run | grep -q "build"; then
            npm run build
          else
            echo "No build script in api-gateway, skipping."
          fi
