name: Keep services alive (Render keep-alive)

# Run every 10 minutes and also allow manual runs
on:
  schedule:
    - cron: '*/10 * * * *'   # every 10 minutes (adjust if you prefer)
  workflow_dispatch: {}

concurrency:
  group: keepalive
  cancel-in-progress: true

jobs:
  ping-services:
    runs-on: ubuntu-latest
    env:
      # Put here the list of services you want to keep alive.
      # Replace these example URLs with your actual Render service URLs.
      KEEP_ALIVE_URLS: |
        https://calculator-backend-api-gateway.onrender.com
        https://calculator-backend-auth-service-1.onrender.com
        https://calculator-backend-operation-service.onrender.com
        https://calculator-backend-record-service.onrender.com
        https://calculator-backend-balance-service.onrender.com

    steps:
      - name: Keep-alive ping (multi-endpoint)
        shell: bash
        run: |
          echo "Keep-alive run started at $(date -u)"
          # Read newline-separated list of URLs from env var
          IFS=$'\n'
          for base in $KEEP_ALIVE_URLS; do
            # Trim whitespace
            url="$(echo $base | tr -d '\r')"
            if [ -z "$url" ]; then
              continue
            fi

            # Prefer to ping /health first (lightweight health endpoint).
            # If /health doesn't return 200, try root / as a fallback.
            correlation="keepalive-$(date +%s)"
            echo "Pinging $url (health) with X-Correlation-Id: $correlation"

            health_status=$(curl -s -o /dev/null -w "%{http_code}" \
              -H "X-Correlation-Id: $correlation" \
              --max-time 10 \
              "$url/health" || true)

            if [ "$health_status" = "200" ]; then
              echo "  OK: $url/health -> 200"
              continue
            fi

            echo "  $url/health returned $health_status. Trying root / ..."
            root_status=$(curl -s -o /dev/null -w "%{http_code}" \
              -H "X-Correlation-Id: $correlation" \
              --max-time 10 \
              "$url" || true)

            # Consider these good-enough success statuses
            if [[ "$root_status" = "200" || "$root_status" = "201" || "$root_status" = "204" || "$root_status" = "301" || "$root_status" = "302" ]]; then
              echo "  OK: $url -> $root_status"
            else
              echo "  WARNING: $url health:$health_status root:$root_status"
            fi
          done

          echo "Keep-alive run finished at $(date -u)"
